[versions]
android-gradle-plugin = "8.2.2"
detekt = "1.23.5"
kotlin = "1.9.22"
dokka = "1.9.10"

compose = "1.5.12"

[libraries]
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
